#ifndef TETRIS_CONST
#define TETRIS_CONST

#define BOARD_HEIGHT 20
#define BOARD_WIDTH 10
#define BLOCK_HEIGHT 4
#define BLOCK_WIDTH 4
#define NUM_BLOCK_STATES 4
#define NUMBER_RECORDS 4
#define INIT_PLAYER_X 3
#define INIT_PLAYER_Y 0
#define LEVEL_MAX 10
#define LEVEL_STEP 600
#define RECORD_FILE_NAME "record.db"

#define DEBOUNCE_TIME 200000
#define KEY_ESCAPE 27
#define KEY_SPACE 32
#define KEY_START 10

#endif  // TETRIS_CONST